### ISSUE TITLE
Admin credentials?

### ISSUE THREAD

**Issue by aptonline** [dcwatson/phxd#4]
Trying to login as admin to setup users but unable too,  Tried the default `admin` or `Admin` in both username and password.

**Comment by dcwatson** [comment]
Try `admin`/`adminpass`. Which branch are you using out of curiosity? Haven't touched this in a while...

**Comment by aptonline** [comment]
Hi, I'm using the docker image (https://hub.docker.com/r/ckb2/phxd).  That password seemed to do something but caused an error requesting login.
```
2022-06-03 23:37:31 ERROR    unhandled exception: [Errno 2] No such file or directory: 'chatlogs/2022-06-03.txt'                                                   
Traceback (most recent call last):                                                                                                                                 
  File "/usr/local/lib/python3.8/site-packages/phxd/server/__init__.py", line 105, in notifyPacket                                                                 
    dispatcher.send(signal=(packet_received, packet.type), sender=self, server=self, user=conn.context, packet=packet)                                             
  File "/usr/local/lib/python3.8/site-packages/pydispatch/dispatcher.py", line 333, in send                                                                        
    response = robustapply.robustApply(                                                                                                                            
  File "/usr/local/lib/python3.8/site-packages/pydispatch/robustapply.py", line 55, in robustApply                                                                 
    return receiver(*arguments, **named)                                                                                                                           
  File "/usr/local/lib/python3.8/site-packages/phxd/server/handlers/user.py", line 56, in handleLogin                                                              
    dispatcher.send(signal=user_login, sender=server, server=server, user=user)                                                                                    
  File "/usr/local/lib/python3.8/site-packages/pydispatch/dispatcher.py", line 333, in send                                                                        
    response = robustapply.robustApply(                                                                                                                            
  File "/usr/local/lib/python3.8/site-packages/pydispatch/robustapply.py", line 55, in robustApply                                                                 
    return receiver(*arguments, **named)                                                                                                                           
  File "/usr/local/lib/python3.8/site-packages/phxd/server/handlers/logger.py", line 97, in logUserJoin                                                            
    chatlog.join(user)                                                                                                                                             
  File "/usr/local/lib/python3.8/site-packages/phxd/server/handlers/logger.py", line 55, in join                                                                   
    self.write(user, "JOIN")                                                                                                                                       
  File "/usr/local/lib/python3.8/site-packages/phxd/server/handlers/logger.py", line 46, in write                                                                  
    self.writeLine("%s\t%s\t%s\t%s" % (user.account.login, user.nick, logtype, line))                                                                              
  File "/usr/local/lib/python3.8/site-packages/phxd/server/handlers/logger.py", line 34, in writeLine                                                              
    self.rotate()                                                                                                                                                  
  File "/usr/local/lib/python3.8/site-packages/phxd/server/handlers/logger.py", line 29, in rotate                                                                 
    self.logfile = codecs.open(path, "a", "utf-8")                                                                                                                 
  File "/usr/local/lib/python3.8/codecs.py", line 905, in open                                                                                                     
    file = builtins.open(filename, mode, buffering)                                                                                                                
FileNotFoundError: [Errno 2] No such file or directory: 'chatlogs/2022-06-03.txt'                                                                                  
Unhandled Error   
```
